// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.14.0
// source: v1/admin/admin.proto

package admin

import (
	_ "github.com/google/gnostic/openapiv3"
	common "github/invokerw/gintos/demo/api/v1/common"
	_ "github/invokerw/gintos/proto/rbac"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageInfo       `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`               // 分页信息
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"` // 登录名
	Phone         *string                `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`       // 手机号
	Status        *common.UserStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=api.common.v1.UserStatus,oneof" json:"status,omitempty"`
	Email         *string                `protobuf:"bytes,5,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListRequest) Reset() {
	*x = GetUserListRequest{}
	mi := &file_v1_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListRequest) ProtoMessage() {}

func (x *GetUserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListRequest.ProtoReflect.Descriptor instead.
func (*GetUserListRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserListRequest) GetPage() *common.PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetUserListRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *GetUserListRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *GetUserListRequest) GetStatus() common.UserStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return common.UserStatus(0)
}

func (x *GetUserListRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *common.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_v1_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUser() *common.User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *common.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_v1_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetUser() *common.User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*common.User         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserListResponse) Reset() {
	*x = GetUserListResponse{}
	mi := &file_v1_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserListResponse) ProtoMessage() {}

func (x *GetUserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserListResponse.ProtoReflect.Descriptor instead.
func (*GetUserListResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserListResponse) GetUsers() []*common.User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*common.User         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsersRequest) Reset() {
	*x = UpdateUsersRequest{}
	mi := &file_v1_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsersRequest) ProtoMessage() {}

func (x *UpdateUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsersRequest.ProtoReflect.Descriptor instead.
func (*UpdateUsersRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUsersRequest) GetUsers() []*common.User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*common.User         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsersResponse) Reset() {
	*x = UpdateUsersResponse{}
	mi := &file_v1_admin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsersResponse) ProtoMessage() {}

func (x *UpdateUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsersResponse.ProtoReflect.Descriptor instead.
func (*UpdateUsersResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUsersResponse) GetUsers() []*common.User {
	if x != nil {
		return x.Users
	}
	return nil
}

type DeleteUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUsersRequest) Reset() {
	*x = DeleteUsersRequest{}
	mi := &file_v1_admin_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUsersRequest) ProtoMessage() {}

func (x *DeleteUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUsersRequest.ProtoReflect.Descriptor instead.
func (*DeleteUsersRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUsersRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type GetRoleListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common.PageInfo       `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`       // 分页信息
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"` // 登录名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleListRequest) Reset() {
	*x = GetRoleListRequest{}
	mi := &file_v1_admin_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleListRequest) ProtoMessage() {}

func (x *GetRoleListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleListRequest.ProtoReflect.Descriptor instead.
func (*GetRoleListRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoleListRequest) GetPage() *common.PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetRoleListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type GetRoleListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*common.Role         `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleListResponse) Reset() {
	*x = GetRoleListResponse{}
	mi := &file_v1_admin_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleListResponse) ProtoMessage() {}

func (x *GetRoleListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleListResponse.ProtoReflect.Descriptor instead.
func (*GetRoleListResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoleListResponse) GetRoles() []*common.Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UpdateRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*common.Role         `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"` // 角色信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRolesRequest) Reset() {
	*x = UpdateRolesRequest{}
	mi := &file_v1_admin_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRolesRequest) ProtoMessage() {}

func (x *UpdateRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRolesRequest.ProtoReflect.Descriptor instead.
func (*UpdateRolesRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRolesRequest) GetRoles() []*common.Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UpdateRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*common.Role         `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRolesResponse) Reset() {
	*x = UpdateRolesResponse{}
	mi := &file_v1_admin_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRolesResponse) ProtoMessage() {}

func (x *UpdateRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRolesResponse.ProtoReflect.Descriptor instead.
func (*UpdateRolesResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRolesResponse) GetRoles() []*common.Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type DeleteRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRolesRequest) Reset() {
	*x = DeleteRolesRequest{}
	mi := &file_v1_admin_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRolesRequest) ProtoMessage() {}

func (x *DeleteRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRolesRequest.ProtoReflect.Descriptor instead.
func (*DeleteRolesRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRolesRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type GetApiInfoListResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ApiTypeMap    map[string]*common.ApiTypeInfo `protobuf:"bytes,2,rep,name=api_type_map,json=apiTypeMap,proto3" json:"api_type_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // API信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiInfoListResponse) Reset() {
	*x = GetApiInfoListResponse{}
	mi := &file_v1_admin_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiInfoListResponse) ProtoMessage() {}

func (x *GetApiInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiInfoListResponse.ProtoReflect.Descriptor instead.
func (*GetApiInfoListResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{12}
}

func (x *GetApiInfoListResponse) GetApiTypeMap() map[string]*common.ApiTypeInfo {
	if x != nil {
		return x.ApiTypeMap
	}
	return nil
}

type RoleGetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"` // 角色名字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGetPolicyRequest) Reset() {
	*x = RoleGetPolicyRequest{}
	mi := &file_v1_admin_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetPolicyRequest) ProtoMessage() {}

func (x *RoleGetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetPolicyRequest.ProtoReflect.Descriptor instead.
func (*RoleGetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{13}
}

func (x *RoleGetPolicyRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type RoleGetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"` // 角色名字
	ApiInfo       []*common.ApiInfo      `protobuf:"bytes,2,rep,name=api_info,json=apiInfo,proto3" json:"api_info,omitempty"`    // API信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGetPolicyResponse) Reset() {
	*x = RoleGetPolicyResponse{}
	mi := &file_v1_admin_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGetPolicyResponse) ProtoMessage() {}

func (x *RoleGetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGetPolicyResponse.ProtoReflect.Descriptor instead.
func (*RoleGetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{14}
}

func (x *RoleGetPolicyResponse) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleGetPolicyResponse) GetApiInfo() []*common.ApiInfo {
	if x != nil {
		return x.ApiInfo
	}
	return nil
}

type RoleUpdatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"` // 角色名字
	ApiName       []string               `protobuf:"bytes,2,rep,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`    // 权限名字
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleUpdatePolicyRequest) Reset() {
	*x = RoleUpdatePolicyRequest{}
	mi := &file_v1_admin_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleUpdatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleUpdatePolicyRequest) ProtoMessage() {}

func (x *RoleUpdatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleUpdatePolicyRequest.ProtoReflect.Descriptor instead.
func (*RoleUpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_v1_admin_admin_proto_rawDescGZIP(), []int{15}
}

func (x *RoleUpdatePolicyRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleUpdatePolicyRequest) GetApiName() []string {
	if x != nil {
		return x.ApiName
	}
	return nil
}

var File_v1_admin_admin_proto protoreflect.FileDescriptor

const file_v1_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x14v1/admin/admin.proto\x12\fapi.v1.admin\x1a\x1cgoogle/api/annotations.proto\x1a\x1copenapi/v3/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14v1/common/user.proto\x1a\x16v1/common/common.proto\x1a\x16rbac/annotations.proto\"\xce\x02\n" +
	"\x12GetUserListRequest\x12?\n" +
	"\x04page\x18\x01 \x01(\v2\x17.api.common.v1.PageInfoB\x12\xbaG\x0f\x92\x02\f分页信息R\x04page\x120\n" +
	"\busername\x18\x02 \x01(\tB\x0f\xbaG\f\x92\x02\t登录名H\x00R\busername\x88\x01\x01\x12*\n" +
	"\x05phone\x18\x03 \x01(\tB\x0f\xbaG\f\x92\x02\t手机号H\x01R\x05phone\x88\x01\x01\x12D\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.api.common.v1.UserStatusB\f\xbaG\t\x92\x02\x06状态H\x02R\x06status\x88\x01\x01\x12'\n" +
	"\x05email\x18\x05 \x01(\tB\f\xbaG\t\x92\x02\x06邮箱H\x03R\x05email\x88\x01\x01B\v\n" +
	"\t_usernameB\b\n" +
	"\x06_phoneB\t\n" +
	"\a_statusB\b\n" +
	"\x06_email\"P\n" +
	"\x11CreateUserRequest\x12;\n" +
	"\x04user\x18\x01 \x01(\v2\x13.api.common.v1.UserB\x12\xbaG\x0f\x92\x02\f用户信息R\x04user\"Q\n" +
	"\x12CreateUserResponse\x12;\n" +
	"\x04user\x18\x01 \x01(\v2\x13.api.common.v1.UserB\x12\xbaG\x0f\x92\x02\f用户信息R\x04user\"@\n" +
	"\x13GetUserListResponse\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.api.common.v1.UserR\x05users\"S\n" +
	"\x12UpdateUsersRequest\x12=\n" +
	"\x05users\x18\x01 \x03(\v2\x13.api.common.v1.UserB\x12\xbaG\x0f\x92\x02\f用户信息R\x05users\"@\n" +
	"\x13UpdateUsersResponse\x12)\n" +
	"\x05users\x18\x01 \x03(\v2\x13.api.common.v1.UserR\x05users\";\n" +
	"\x12DeleteUsersRequest\x12%\n" +
	"\x05names\x18\x01 \x03(\tB\x0f\xbaG\f\x92\x02\t用户名R\x05names\"\x88\x01\n" +
	"\x12GetRoleListRequest\x12?\n" +
	"\x04page\x18\x01 \x01(\v2\x17.api.common.v1.PageInfoB\x12\xbaG\x0f\x92\x02\f分页信息R\x04page\x12(\n" +
	"\x04name\x18\x02 \x01(\tB\x0f\xbaG\f\x92\x02\t角色名H\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"@\n" +
	"\x13GetRoleListResponse\x12)\n" +
	"\x05roles\x18\x01 \x03(\v2\x13.api.common.v1.RoleR\x05roles\"S\n" +
	"\x12UpdateRolesRequest\x12=\n" +
	"\x05roles\x18\x01 \x03(\v2\x13.api.common.v1.RoleB\x12\xbaG\x0f\x92\x02\f角色信息R\x05roles\"@\n" +
	"\x13UpdateRolesResponse\x12)\n" +
	"\x05roles\x18\x01 \x03(\v2\x13.api.common.v1.RoleR\x05roles\">\n" +
	"\x12DeleteRolesRequest\x12(\n" +
	"\x05names\x18\x01 \x03(\tB\x12\xbaG\x0f\x92\x02\f角色名字R\x05names\"\xe2\x01\n" +
	"\x16GetApiInfoListResponse\x12m\n" +
	"\fapi_type_map\x18\x02 \x03(\v24.api.v1.admin.GetApiInfoListResponse.ApiTypeMapEntryB\x15\xbaG\x12\x92\x02\x0f分类API数据R\n" +
	"apiTypeMap\x1aY\n" +
	"\x0fApiTypeMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.api.common.v1.ApiTypeInfoR\x05value:\x028\x01\"G\n" +
	"\x14RoleGetPolicyRequest\x12/\n" +
	"\trole_name\x18\x01 \x01(\tB\x12\xbaG\x0f\x92\x02\f角色名字R\broleName\"\x8c\x01\n" +
	"\x15RoleGetPolicyResponse\x12/\n" +
	"\trole_name\x18\x01 \x01(\tB\x12\xbaG\x0f\x92\x02\f角色名字R\broleName\x12B\n" +
	"\bapi_info\x18\x02 \x03(\v2\x16.api.common.v1.ApiInfoB\x0f\xbaG\f\x92\x02\tAPI信息R\aapiInfo\"w\n" +
	"\x17RoleUpdatePolicyRequest\x12/\n" +
	"\trole_name\x18\x01 \x01(\tB\x12\xbaG\x0f\x92\x02\f角色名字R\broleName\x12+\n" +
	"\bapi_name\x18\x02 \x03(\tB\x10\xbaG\r\x92\x02\n" +
	"api 名称R\aapiName2\x94\x0e\n" +
	"\x05Admin\x12\x90\x01\n" +
	"\n" +
	"CreateUser\x12\x1f.api.v1.admin.CreateUserRequest\x1a .api.v1.admin.CreateUserResponse\"?\xbaG\x02Z\x00\x82}\f创建用户\x8a}\x04user\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/admin/create_user\x12\x9b\x01\n" +
	"\vGetUserList\x12 .api.v1.admin.GetUserListRequest\x1a!.api.v1.admin.GetUserListResponse\"G\xbaG\x02Z\x00\x82}\x12获取用户列表\x8a}\x04user\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/admin/get_user_list\x12\x94\x01\n" +
	"\vUpdateUsers\x12 .api.v1.admin.UpdateUsersRequest\x1a!.api.v1.admin.UpdateUsersResponse\"@\xbaG\x02Z\x00\x82}\f更新用户\x8a}\x04user\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/admin/update_users\x12\x89\x01\n" +
	"\vDeleteUsers\x12 .api.v1.admin.DeleteUsersRequest\x1a\x16.google.protobuf.Empty\"@\xbaG\x02Z\x00\x82}\f删除用户\x8a}\x04user\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/admin/delete_users\x12\x86\x01\n" +
	"\fGetUserCount\x12\x16.google.protobuf.Empty\x1a\x17.api.common.v1.IntValue\"E\xbaG\x02Z\x00\x82}\x12获取用户数量\x8a}\x04user\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/admin/get_user_count\x12\x9b\x01\n" +
	"\vGetRoleList\x12 .api.v1.admin.GetRoleListRequest\x1a!.api.v1.admin.GetRoleListResponse\"G\xbaG\x02Z\x00\x82}\x12获取角色列表\x8a}\x04role\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/admin/get_role_list\x12\x94\x01\n" +
	"\vUpdateRoles\x12 .api.v1.admin.UpdateRolesRequest\x1a!.api.v1.admin.UpdateRolesResponse\"@\xbaG\x02Z\x00\x82}\f更新角色\x8a}\x04role\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/admin/update_roles\x12\x89\x01\n" +
	"\vDeleteRoles\x12 .api.v1.admin.DeleteRolesRequest\x1a\x16.google.protobuf.Empty\"@\xbaG\x02Z\x00\x82}\f删除角色\x8a}\x04role\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/admin/delete_roles\x12\x86\x01\n" +
	"\fGetRoleCount\x12\x16.google.protobuf.Empty\x1a\x17.api.common.v1.IntValue\"E\xbaG\x02Z\x00\x82}\x12获取角色数量\x8a}\x04role\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/admin/get_role_count\x12\x96\x01\n" +
	"\x0eGetApiInfoList\x12\x16.google.protobuf.Empty\x1a$.api.v1.admin.GetApiInfoListResponse\"F\xbaG\x02Z\x00\x82}\x15获取API信息列表\x8a}\x04rbac\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/admin/get_api_info\x12\xab\x01\n" +
	"\rRoleGetPolicy\x12\".api.v1.admin.RoleGetPolicyRequest\x1a#.api.v1.admin.RoleGetPolicyResponse\"Q\xbaG\x02Z\x00\x82}\x12获取角色权限\x8a}\x04rbac\x82\xd3\xe4\x93\x02*\x12(/api/v1/admin/role_get_policy/:role_name\x12\x9c\x01\n" +
	"\x10RoleUpdatePolicy\x12%.api.v1.admin.RoleUpdatePolicyRequest\x1a\x16.google.protobuf.Empty\"I\xbaG\x02Z\x00\x82}\x12角色更新权限\x8a}\x04rbac\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/admin/role_add_policyB0Z.github/invokerw/gintos/demo/api/v1/admin;adminb\x06proto3"

var (
	file_v1_admin_admin_proto_rawDescOnce sync.Once
	file_v1_admin_admin_proto_rawDescData []byte
)

func file_v1_admin_admin_proto_rawDescGZIP() []byte {
	file_v1_admin_admin_proto_rawDescOnce.Do(func() {
		file_v1_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_admin_proto_rawDesc), len(file_v1_admin_admin_proto_rawDesc)))
	})
	return file_v1_admin_admin_proto_rawDescData
}

var file_v1_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_v1_admin_admin_proto_goTypes = []any{
	(*GetUserListRequest)(nil),      // 0: api.v1.admin.GetUserListRequest
	(*CreateUserRequest)(nil),       // 1: api.v1.admin.CreateUserRequest
	(*CreateUserResponse)(nil),      // 2: api.v1.admin.CreateUserResponse
	(*GetUserListResponse)(nil),     // 3: api.v1.admin.GetUserListResponse
	(*UpdateUsersRequest)(nil),      // 4: api.v1.admin.UpdateUsersRequest
	(*UpdateUsersResponse)(nil),     // 5: api.v1.admin.UpdateUsersResponse
	(*DeleteUsersRequest)(nil),      // 6: api.v1.admin.DeleteUsersRequest
	(*GetRoleListRequest)(nil),      // 7: api.v1.admin.GetRoleListRequest
	(*GetRoleListResponse)(nil),     // 8: api.v1.admin.GetRoleListResponse
	(*UpdateRolesRequest)(nil),      // 9: api.v1.admin.UpdateRolesRequest
	(*UpdateRolesResponse)(nil),     // 10: api.v1.admin.UpdateRolesResponse
	(*DeleteRolesRequest)(nil),      // 11: api.v1.admin.DeleteRolesRequest
	(*GetApiInfoListResponse)(nil),  // 12: api.v1.admin.GetApiInfoListResponse
	(*RoleGetPolicyRequest)(nil),    // 13: api.v1.admin.RoleGetPolicyRequest
	(*RoleGetPolicyResponse)(nil),   // 14: api.v1.admin.RoleGetPolicyResponse
	(*RoleUpdatePolicyRequest)(nil), // 15: api.v1.admin.RoleUpdatePolicyRequest
	nil,                             // 16: api.v1.admin.GetApiInfoListResponse.ApiTypeMapEntry
	(*common.PageInfo)(nil),         // 17: api.common.v1.PageInfo
	(common.UserStatus)(0),          // 18: api.common.v1.UserStatus
	(*common.User)(nil),             // 19: api.common.v1.User
	(*common.Role)(nil),             // 20: api.common.v1.Role
	(*common.ApiInfo)(nil),          // 21: api.common.v1.ApiInfo
	(*common.ApiTypeInfo)(nil),      // 22: api.common.v1.ApiTypeInfo
	(*emptypb.Empty)(nil),           // 23: google.protobuf.Empty
	(*common.IntValue)(nil),         // 24: api.common.v1.IntValue
}
var file_v1_admin_admin_proto_depIdxs = []int32{
	17, // 0: api.v1.admin.GetUserListRequest.page:type_name -> api.common.v1.PageInfo
	18, // 1: api.v1.admin.GetUserListRequest.status:type_name -> api.common.v1.UserStatus
	19, // 2: api.v1.admin.CreateUserRequest.user:type_name -> api.common.v1.User
	19, // 3: api.v1.admin.CreateUserResponse.user:type_name -> api.common.v1.User
	19, // 4: api.v1.admin.GetUserListResponse.users:type_name -> api.common.v1.User
	19, // 5: api.v1.admin.UpdateUsersRequest.users:type_name -> api.common.v1.User
	19, // 6: api.v1.admin.UpdateUsersResponse.users:type_name -> api.common.v1.User
	17, // 7: api.v1.admin.GetRoleListRequest.page:type_name -> api.common.v1.PageInfo
	20, // 8: api.v1.admin.GetRoleListResponse.roles:type_name -> api.common.v1.Role
	20, // 9: api.v1.admin.UpdateRolesRequest.roles:type_name -> api.common.v1.Role
	20, // 10: api.v1.admin.UpdateRolesResponse.roles:type_name -> api.common.v1.Role
	16, // 11: api.v1.admin.GetApiInfoListResponse.api_type_map:type_name -> api.v1.admin.GetApiInfoListResponse.ApiTypeMapEntry
	21, // 12: api.v1.admin.RoleGetPolicyResponse.api_info:type_name -> api.common.v1.ApiInfo
	22, // 13: api.v1.admin.GetApiInfoListResponse.ApiTypeMapEntry.value:type_name -> api.common.v1.ApiTypeInfo
	1,  // 14: api.v1.admin.Admin.CreateUser:input_type -> api.v1.admin.CreateUserRequest
	0,  // 15: api.v1.admin.Admin.GetUserList:input_type -> api.v1.admin.GetUserListRequest
	4,  // 16: api.v1.admin.Admin.UpdateUsers:input_type -> api.v1.admin.UpdateUsersRequest
	6,  // 17: api.v1.admin.Admin.DeleteUsers:input_type -> api.v1.admin.DeleteUsersRequest
	23, // 18: api.v1.admin.Admin.GetUserCount:input_type -> google.protobuf.Empty
	7,  // 19: api.v1.admin.Admin.GetRoleList:input_type -> api.v1.admin.GetRoleListRequest
	9,  // 20: api.v1.admin.Admin.UpdateRoles:input_type -> api.v1.admin.UpdateRolesRequest
	11, // 21: api.v1.admin.Admin.DeleteRoles:input_type -> api.v1.admin.DeleteRolesRequest
	23, // 22: api.v1.admin.Admin.GetRoleCount:input_type -> google.protobuf.Empty
	23, // 23: api.v1.admin.Admin.GetApiInfoList:input_type -> google.protobuf.Empty
	13, // 24: api.v1.admin.Admin.RoleGetPolicy:input_type -> api.v1.admin.RoleGetPolicyRequest
	15, // 25: api.v1.admin.Admin.RoleUpdatePolicy:input_type -> api.v1.admin.RoleUpdatePolicyRequest
	2,  // 26: api.v1.admin.Admin.CreateUser:output_type -> api.v1.admin.CreateUserResponse
	3,  // 27: api.v1.admin.Admin.GetUserList:output_type -> api.v1.admin.GetUserListResponse
	5,  // 28: api.v1.admin.Admin.UpdateUsers:output_type -> api.v1.admin.UpdateUsersResponse
	23, // 29: api.v1.admin.Admin.DeleteUsers:output_type -> google.protobuf.Empty
	24, // 30: api.v1.admin.Admin.GetUserCount:output_type -> api.common.v1.IntValue
	8,  // 31: api.v1.admin.Admin.GetRoleList:output_type -> api.v1.admin.GetRoleListResponse
	10, // 32: api.v1.admin.Admin.UpdateRoles:output_type -> api.v1.admin.UpdateRolesResponse
	23, // 33: api.v1.admin.Admin.DeleteRoles:output_type -> google.protobuf.Empty
	24, // 34: api.v1.admin.Admin.GetRoleCount:output_type -> api.common.v1.IntValue
	12, // 35: api.v1.admin.Admin.GetApiInfoList:output_type -> api.v1.admin.GetApiInfoListResponse
	14, // 36: api.v1.admin.Admin.RoleGetPolicy:output_type -> api.v1.admin.RoleGetPolicyResponse
	23, // 37: api.v1.admin.Admin.RoleUpdatePolicy:output_type -> google.protobuf.Empty
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_admin_admin_proto_init() }
func file_v1_admin_admin_proto_init() {
	if File_v1_admin_admin_proto != nil {
		return
	}
	file_v1_admin_admin_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_admin_admin_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_admin_proto_rawDesc), len(file_v1_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_admin_admin_proto_goTypes,
		DependencyIndexes: file_v1_admin_admin_proto_depIdxs,
		MessageInfos:      file_v1_admin_admin_proto_msgTypes,
	}.Build()
	File_v1_admin_admin_proto = out.File
	file_v1_admin_admin_proto_goTypes = nil
	file_v1_admin_admin_proto_depIdxs = nil
}
