// Code generated by protoc-gen-go-gin. DO NOT EDIT.
// versions:
// - protoc-gen-go-gin v1.0.0
// - protoc             v3.14.0
// source: v1/admin/admin.proto

package admin

import (
	gin "github.com/gin-gonic/gin"
	resp "github/invokerw/gintos/common/resp"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(gin.Context)
var _ = new(resp.Response)

const OperationAdminGetUserList = "/api.auth.v1.Admin/GetUserList"

type IAdminServer interface {
	// GetUserList 登录
	GetUserList(*gin.Context, *GetUserListRequest) (*GetUserListResponse, error)
}

func RegisterAdminServer(r gin.IRoutes, srv IAdminServer) {
	r.POST("/admin/v1/get_user_list", _Admin_GetUserList0_HTTP_Handler(srv))
}

func _Admin_GetUserList0_HTTP_Handler(srv IAdminServer) func(ctx *gin.Context) {
	return func(ctx *gin.Context) {
		var in GetUserListRequest
		if err := ctx.ShouldBindJSON(&in); err != nil {
			resp.FailWithMessage(ctx, err.Error())
			return
		}
		if err := ctx.BindQuery(&in); err != nil {
			resp.FailWithMessage(ctx, err.Error())
			return
		}
		// http.SetOperation(ctx, OperationAdminGetUserList)
		reply, err := srv.GetUserList(ctx, &in)
		if err != nil {
			resp.FailWithError(ctx, err)
			return
		}
		resp.OkWithData(ctx, reply)
	}
}
