// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.14.0
// source: v1/common/user.proto

package common

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户权限
type UserAuthority int32

const (
	UserAuthority_SYS_ADMIN     UserAuthority = 0 // 系统超级用户
	UserAuthority_SYS_MANAGER   UserAuthority = 1 // 系统管理员
	UserAuthority_CUSTOMER_USER UserAuthority = 2 // 普通用户
	UserAuthority_GUEST_USER    UserAuthority = 3 // 游客
)

// Enum value maps for UserAuthority.
var (
	UserAuthority_name = map[int32]string{
		0: "SYS_ADMIN",
		1: "SYS_MANAGER",
		2: "CUSTOMER_USER",
		3: "GUEST_USER",
	}
	UserAuthority_value = map[string]int32{
		"SYS_ADMIN":     0,
		"SYS_MANAGER":   1,
		"CUSTOMER_USER": 2,
		"GUEST_USER":    3,
	}
)

func (x UserAuthority) Enum() *UserAuthority {
	p := new(UserAuthority)
	*p = x
	return p
}

func (x UserAuthority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAuthority) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_user_proto_enumTypes[0].Descriptor()
}

func (UserAuthority) Type() protoreflect.EnumType {
	return &file_v1_common_user_proto_enumTypes[0]
}

func (x UserAuthority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAuthority.Descriptor instead.
func (UserAuthority) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_user_proto_rawDescGZIP(), []int{0}
}

// 用户性别
type UserGender int32

const (
	UserGender_SECRET UserGender = 0 // 未知
	UserGender_MALE   UserGender = 1 // 男性
	UserGender_FEMALE UserGender = 2 // 女性
)

// Enum value maps for UserGender.
var (
	UserGender_name = map[int32]string{
		0: "SECRET",
		1: "MALE",
		2: "FEMALE",
	}
	UserGender_value = map[string]int32{
		"SECRET": 0,
		"MALE":   1,
		"FEMALE": 2,
	}
)

func (x UserGender) Enum() *UserGender {
	p := new(UserGender)
	*p = x
	return p
}

func (x UserGender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserGender) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_user_proto_enumTypes[1].Descriptor()
}

func (UserGender) Type() protoreflect.EnumType {
	return &file_v1_common_user_proto_enumTypes[1]
}

func (x UserGender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserGender.Descriptor instead.
func (UserGender) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_user_proto_rawDescGZIP(), []int{1}
}

// 用户状态
type UserStatus int32

const (
	UserStatus_OFF UserStatus = 0
	UserStatus_ON  UserStatus = 1
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "OFF",
		1: "ON",
	}
	UserStatus_value = map[string]int32{
		"OFF": 0,
		"ON":  1,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_user_proto_enumTypes[2].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_v1_common_user_proto_enumTypes[2]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_user_proto_rawDescGZIP(), []int{2}
}

// 用户
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`                                                 // 用户ID
	RoleName      *string                `protobuf:"bytes,2,opt,name=role_name,proto3,oneof" json:"role_name,omitempty"`                                    // 角色名称
	CreateBy      *uint64                `protobuf:"varint,7,opt,name=create_by,proto3,oneof" json:"create_by,omitempty"`                                   // 创建者ID
	UpdateBy      *uint64                `protobuf:"varint,8,opt,name=update_by,proto3,oneof" json:"update_by,omitempty"`                                   // 更新者ID
	UserName      *string                `protobuf:"bytes,10,opt,name=user_name,proto3,oneof" json:"user_name,omitempty"`                                   // 登录名
	Password      *string                `protobuf:"bytes,11,opt,name=password,proto3,oneof" json:"password,omitempty"`                                     // 密码
	NickName      *string                `protobuf:"bytes,12,opt,name=nick_name,proto3,oneof" json:"nick_name,omitempty"`                                   // 昵称
	Avatar        *string                `protobuf:"bytes,13,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`                                         // 头像
	Email         *string                `protobuf:"bytes,14,opt,name=email,proto3,oneof" json:"email,omitempty"`                                           // 邮箱
	Mobile        *string                `protobuf:"bytes,15,opt,name=mobile,proto3,oneof" json:"mobile,omitempty"`                                         // 手机号
	Gender        *UserGender            `protobuf:"varint,17,opt,name=gender,proto3,enum=api.common.v1.UserGender,oneof" json:"gender,omitempty"`          // 性别
	Remark        *string                `protobuf:"bytes,21,opt,name=remark,proto3,oneof" json:"remark,omitempty"`                                         // 备注名
	LastLoginTime *int64                 `protobuf:"varint,30,opt,name=last_login_time,proto3,oneof" json:"last_login_time,omitempty"`                      // 最后登录时间
	Status        *UserStatus            `protobuf:"varint,32,opt,name=status,proto3,enum=api.common.v1.UserStatus,oneof" json:"status,omitempty"`          // 用户状态
	Authority     *UserAuthority         `protobuf:"varint,33,opt,name=authority,proto3,enum=api.common.v1.UserAuthority,oneof" json:"authority,omitempty"` // 权限
	Roles         []string               `protobuf:"bytes,34,rep,name=roles,proto3" json:"roles,omitempty"`                                                 // 角色码
	CreateTime    *int64                 `protobuf:"varint,200,opt,name=create_time,proto3,oneof" json:"create_time,omitempty"`                             // 创建时间
	UpdateTime    *int64                 `protobuf:"varint,201,opt,name=update_time,proto3,oneof" json:"update_time,omitempty"`                             // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_common_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_common_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *User) GetRoleName() string {
	if x != nil && x.RoleName != nil {
		return *x.RoleName
	}
	return ""
}

func (x *User) GetCreateBy() uint64 {
	if x != nil && x.CreateBy != nil {
		return *x.CreateBy
	}
	return 0
}

func (x *User) GetUpdateBy() uint64 {
	if x != nil && x.UpdateBy != nil {
		return *x.UpdateBy
	}
	return 0
}

func (x *User) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *User) GetNickName() string {
	if x != nil && x.NickName != nil {
		return *x.NickName
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *User) GetMobile() string {
	if x != nil && x.Mobile != nil {
		return *x.Mobile
	}
	return ""
}

func (x *User) GetGender() UserGender {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return UserGender_SECRET
}

func (x *User) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *User) GetLastLoginTime() int64 {
	if x != nil && x.LastLoginTime != nil {
		return *x.LastLoginTime
	}
	return 0
}

func (x *User) GetStatus() UserStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return UserStatus_OFF
}

func (x *User) GetAuthority() UserAuthority {
	if x != nil && x.Authority != nil {
		return *x.Authority
	}
	return UserAuthority_SYS_ADMIN
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetCreateTime() int64 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

func (x *User) GetUpdateTime() int64 {
	if x != nil && x.UpdateTime != nil {
		return *x.UpdateTime
	}
	return 0
}

// Role
type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"` // 角色ID
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Desc          *string                `protobuf:"bytes,3,opt,name=desc,proto3,oneof" json:"desc,omitempty"`
	ParentId      *uint64                `protobuf:"varint,4,opt,name=parent_id,json=parentID,proto3,oneof" json:"parent_id,omitempty"`
	SortId        *int32                 `protobuf:"varint,5,opt,name=sort_id,json=sortID,proto3,oneof" json:"sort_id,omitempty"`
	CreateTime    *int64                 `protobuf:"varint,200,opt,name=create_time,json=createTime,proto3,oneof" json:"create_time,omitempty"` // 创建时间
	UpdateTime    *int64                 `protobuf:"varint,201,opt,name=update_time,json=updateTime,proto3,oneof" json:"update_time,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_v1_common_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_v1_common_user_proto_rawDescGZIP(), []int{1}
}

func (x *Role) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Role) GetDesc() string {
	if x != nil && x.Desc != nil {
		return *x.Desc
	}
	return ""
}

func (x *Role) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *Role) GetSortId() int32 {
	if x != nil && x.SortId != nil {
		return *x.SortId
	}
	return 0
}

func (x *Role) GetCreateTime() int64 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

func (x *Role) GetUpdateTime() int64 {
	if x != nil && x.UpdateTime != nil {
		return *x.UpdateTime
	}
	return 0
}

var File_v1_common_user_proto protoreflect.FileDescriptor

const file_v1_common_user_proto_rawDesc = "" +
	"\n" +
	"\x14v1/common/user.proto\x12\rapi.common.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1copenapi/v3/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\t\n" +
	"\x04User\x12#\n" +
	"\x02id\x18\x01 \x01(\x04B\x0e\xbaG\v\x92\x02\b用户IDH\x00R\x02id\x88\x01\x01\x125\n" +
	"\trole_name\x18\x02 \x01(\tB\x12\xbaG\x0f\x92\x02\f角色名称H\x01R\trole_name\x88\x01\x01\x124\n" +
	"\tcreate_by\x18\a \x01(\x04B\x11\xbaG\x0e\x92\x02\v创建者IDH\x02R\tcreate_by\x88\x01\x01\x124\n" +
	"\tupdate_by\x18\b \x01(\x04B\x11\xbaG\x0e\x92\x02\v更新者IDH\x03R\tupdate_by\x88\x01\x01\x122\n" +
	"\tuser_name\x18\n" +
	" \x01(\tB\x0f\xbaG\f\x92\x02\t登录名H\x04R\tuser_name\x88\x01\x01\x12-\n" +
	"\bpassword\x18\v \x01(\tB\f\xbaG\t\x92\x02\x06密码H\x05R\bpassword\x88\x01\x01\x12/\n" +
	"\tnick_name\x18\f \x01(\tB\f\xbaG\t\x92\x02\x06昵称H\x06R\tnick_name\x88\x01\x01\x12)\n" +
	"\x06avatar\x18\r \x01(\tB\f\xbaG\t\x92\x02\x06头像H\aR\x06avatar\x88\x01\x01\x12'\n" +
	"\x05email\x18\x0e \x01(\tB\f\xbaG\t\x92\x02\x06邮箱H\bR\x05email\x88\x01\x01\x12,\n" +
	"\x06mobile\x18\x0f \x01(\tB\x0f\xbaG\f\x92\x02\t手机号H\tR\x06mobile\x88\x01\x01\x12D\n" +
	"\x06gender\x18\x11 \x01(\x0e2\x19.api.common.v1.UserGenderB\f\xbaG\t\x92\x02\x06性别H\n" +
	"R\x06gender\x88\x01\x01\x12,\n" +
	"\x06remark\x18\x15 \x01(\tB\x0f\xbaG\f\x92\x02\t备注名H\vR\x06remark\x88\x01\x01\x12G\n" +
	"\x0flast_login_time\x18\x1e \x01(\x03B\x18\xbaG\x15\x92\x02\x12最后登录时间H\fR\x0flast_login_time\x88\x01\x01\x12`\n" +
	"\x06status\x18  \x01(\x0e2\x19.api.common.v1.UserStatusB(\xbaG%\xc2\x01\x04\x12\x02ON\xc2\x01\x05\x12\x03OFF\x8a\x02\x04\x1a\x02ON\x92\x02\f用户状态H\rR\x06status\x88\x01\x01\x12_\n" +
	"\tauthority\x18! \x01(\x0e2\x1c.api.common.v1.UserAuthorityB\x1e\xbaG\x1b\x8a\x02\x0f\x1a\rCUSTOMER_USER\x92\x02\x06权限H\x0eR\tauthority\x88\x01\x01\x12\"\n" +
	"\x05roles\x18\" \x03(\tB\f\xbaG\t\x92\x02\x06角色R\x05roles\x12:\n" +
	"\vcreate_time\x18\xc8\x01 \x01(\x03B\x12\xbaG\x0f\x92\x02\f创建时间H\x0fR\vcreate_time\x88\x01\x01\x12:\n" +
	"\vupdate_time\x18\xc9\x01 \x01(\x03B\x12\xbaG\x0f\x92\x02\f更新时间H\x10R\vupdate_time\x88\x01\x01B\x05\n" +
	"\x03_idB\f\n" +
	"\n" +
	"_role_nameB\f\n" +
	"\n" +
	"_create_byB\f\n" +
	"\n" +
	"_update_byB\f\n" +
	"\n" +
	"_user_nameB\v\n" +
	"\t_passwordB\f\n" +
	"\n" +
	"_nick_nameB\t\n" +
	"\a_avatarB\b\n" +
	"\x06_emailB\t\n" +
	"\a_mobileB\t\n" +
	"\a_genderB\t\n" +
	"\a_remarkB\x12\n" +
	"\x10_last_login_timeB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_authorityB\x0e\n" +
	"\f_create_timeB\x0e\n" +
	"\f_update_time\"\xb1\x03\n" +
	"\x04Role\x12#\n" +
	"\x02id\x18\x01 \x01(\x04B\x0e\xbaG\v\x92\x02\b角色IDH\x00R\x02id\x88\x01\x01\x12+\n" +
	"\x04name\x18\x02 \x01(\tB\x12\xbaG\x0f\x92\x02\f角色名称H\x01R\x04name\x88\x01\x01\x12+\n" +
	"\x04desc\x18\x03 \x01(\tB\x12\xbaG\x0f\x92\x02\f角色描述H\x02R\x04desc\x88\x01\x01\x123\n" +
	"\tparent_id\x18\x04 \x01(\x04B\x11\xbaG\x0e\x92\x02\v父角色IDH\x03R\bparentID\x88\x01\x01\x12,\n" +
	"\asort_id\x18\x05 \x01(\x05B\x0e\xbaG\v\x92\x02\b排序IDH\x04R\x06sortID\x88\x01\x01\x129\n" +
	"\vcreate_time\x18\xc8\x01 \x01(\x03B\x12\xbaG\x0f\x92\x02\f创建时间H\x05R\n" +
	"createTime\x88\x01\x01\x129\n" +
	"\vupdate_time\x18\xc9\x01 \x01(\x03B\x12\xbaG\x0f\x92\x02\f更新时间H\x06R\n" +
	"updateTime\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_descB\f\n" +
	"\n" +
	"_parent_idB\n" +
	"\n" +
	"\b_sort_idB\x0e\n" +
	"\f_create_timeB\x0e\n" +
	"\f_update_time*R\n" +
	"\rUserAuthority\x12\r\n" +
	"\tSYS_ADMIN\x10\x00\x12\x0f\n" +
	"\vSYS_MANAGER\x10\x01\x12\x11\n" +
	"\rCUSTOMER_USER\x10\x02\x12\x0e\n" +
	"\n" +
	"GUEST_USER\x10\x03*.\n" +
	"\n" +
	"UserGender\x12\n" +
	"\n" +
	"\x06SECRET\x10\x00\x12\b\n" +
	"\x04MALE\x10\x01\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x02*\x1d\n" +
	"\n" +
	"UserStatus\x12\a\n" +
	"\x03OFF\x10\x00\x12\x06\n" +
	"\x02ON\x10\x01B2Z0github/invokerw/gintos/demo/api/v1/common;commonb\x06proto3"

var (
	file_v1_common_user_proto_rawDescOnce sync.Once
	file_v1_common_user_proto_rawDescData []byte
)

func file_v1_common_user_proto_rawDescGZIP() []byte {
	file_v1_common_user_proto_rawDescOnce.Do(func() {
		file_v1_common_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_common_user_proto_rawDesc), len(file_v1_common_user_proto_rawDesc)))
	})
	return file_v1_common_user_proto_rawDescData
}

var file_v1_common_user_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_v1_common_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_common_user_proto_goTypes = []any{
	(UserAuthority)(0), // 0: api.common.v1.UserAuthority
	(UserGender)(0),    // 1: api.common.v1.UserGender
	(UserStatus)(0),    // 2: api.common.v1.UserStatus
	(*User)(nil),       // 3: api.common.v1.User
	(*Role)(nil),       // 4: api.common.v1.Role
}
var file_v1_common_user_proto_depIdxs = []int32{
	1, // 0: api.common.v1.User.gender:type_name -> api.common.v1.UserGender
	2, // 1: api.common.v1.User.status:type_name -> api.common.v1.UserStatus
	0, // 2: api.common.v1.User.authority:type_name -> api.common.v1.UserAuthority
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_common_user_proto_init() }
func file_v1_common_user_proto_init() {
	if File_v1_common_user_proto != nil {
		return
	}
	file_v1_common_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_common_user_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_common_user_proto_rawDesc), len(file_v1_common_user_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_common_user_proto_goTypes,
		DependencyIndexes: file_v1_common_user_proto_depIdxs,
		EnumInfos:         file_v1_common_user_proto_enumTypes,
		MessageInfos:      file_v1_common_user_proto_msgTypes,
	}.Build()
	File_v1_common_user_proto = out.File
	file_v1_common_user_proto_goTypes = nil
	file_v1_common_user_proto_depIdxs = nil
}
