// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.14.0
// source: rbac/annotations.proto

package rbac

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_rbac_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         2000,
		Name:          "rbac.comment",
		Tag:           "bytes,2000,opt,name=comment",
		Filename:      "rbac/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string comment = 2000;
	E_Comment = &file_rbac_annotations_proto_extTypes[0] // 有评论才会生成 rbac 信息
)

var File_rbac_annotations_proto protoreflect.FileDescriptor

const file_rbac_annotations_proto_rawDesc = "" +
	"\n" +
	"\x16rbac/annotations.proto\x12\x04rbac\x1a google/protobuf/descriptor.proto:9\n" +
	"\acomment\x12\x1e.google.protobuf.MethodOptions\x18\xd0\x0f \x01(\tR\acommentB(Z&github/invokerw/gintos/proto/rbac;rbacb\x06proto3"

var file_rbac_annotations_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
}
var file_rbac_annotations_proto_depIdxs = []int32{
	0, // 0: rbac.comment:extendee -> google.protobuf.MethodOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rbac_annotations_proto_init() }
func file_rbac_annotations_proto_init() {
	if File_rbac_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rbac_annotations_proto_rawDesc), len(file_rbac_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_rbac_annotations_proto_goTypes,
		DependencyIndexes: file_rbac_annotations_proto_depIdxs,
		ExtensionInfos:    file_rbac_annotations_proto_extTypes,
	}.Build()
	File_rbac_annotations_proto = out.File
	file_rbac_annotations_proto_goTypes = nil
	file_rbac_annotations_proto_depIdxs = nil
}
