server:
  http:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  database:
    driver: sqlite3
    source: file:ent.db?_fk=1
  redis:
    addr: 127.0.0.1:6379
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
